version: "3.8"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database
    ports:
      - 5432:5432
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
  app:
    image: node-app
    ports:
      - 3000:3000
