version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: user123
      POSTGRES_DB: db123
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
  app:
    image: node-app
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
